create stocks chart
Abdull-Rauf/stocks pull request #4
Opened 2021-10-13 10:39 UTC by Abdull-Rauf

2021-10-13 12:20 UTC, Farhan-Nazir requested changes

2021-10-13 12:20 UTC, Farhan-Nazir commented on src/components/charts/StocksChart.tsx
> +  const canvas = document.createElement("canvas");
You don't need to create any canvas, chart library will create one for the component

2021-10-13 12:20 UTC, Farhan-Nazir commented on src/services/stocks/getStocksData.service.ts
> +    console.error();
no console....

2021-10-13 12:20 UTC, Farhan-Nazir commented on src/views/StocksChartScreen.tsx
> +      style={{
no in-line styling allowed, Please create scss module for styling

2021-10-13 12:20 UTC, Farhan-Nazir commented on src/views/StocksChartScreen.tsx
> +import { FC, useState, useEffect } from "react";
File name should be match your component name, if the folder name is `views` then file name should be `StockChart.view.tsx`. 
`StockChart` is not a correct name for page, A page can be `Home | Dashboard ` or something but the StockChart is component

2021-10-13 12:20 UTC, Farhan-Nazir commented on src/components/charts/StocksChart.tsx
> +    title: {
try this.
```suggestion
    options: {
        plugins: {
            title: {
                display: true,
                text: 'Custom Chart Title'
            }
        }
    }
```

2021-10-13 12:20 UTC, Farhan-Nazir commented on src/components/charts/StocksChart.tsx
> +  const ctx: any = canvas.getContext("2d");
can you try some type here?

2021-10-13 18:04 UTC, Farhan-Nazir requested changes

2021-10-13 18:04 UTC, Farhan-Nazir commented on src/components/charts/StocksChart.tsx
> +        backgroundColor: gradient,
can you try this?
```suggestion
        backgroundColor: 'linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(9,9,121,1) 35%, rgba(0,212,255,1) 100%)',
```

2021-10-14 15:36 UTC, Abdull-Rauf commented on src/components/charts/StocksChart.tsx
> +  const canvas = document.createElement("canvas");
I tried but it didn't work for me.

2021-10-14 15:39 UTC, Abdull-Rauf commented on src/components/charts/StocksChart.tsx
> +        backgroundColor: gradient,
I have tried this but didn't work.

2021-10-17 16:26 UTC, merged