add date range options
Abdull-Rauf/stocks pull request #5
Opened 2021-10-23 12:58 UTC by Abdull-Rauf

![stocks-before](https://user-images.githubusercontent.com/45719544/138557449-319a4152-4ebc-4181-84cc-b825c96a651a.jpg)
![stocks-now](https://user-images.githubusercontent.com/45719544/138557451-0c741387-c2aa-4139-b19d-f854deaca0b2.jpg)

2021-10-24 19:01 UTC, Farhan-Nazir requested changes

2021-10-24 19:01 UTC, Farhan-Nazir commented on src/components/DateRange.tsx
> +  const dateRangeData: any = [
no any type please.

2021-10-24 19:01 UTC, Farhan-Nazir commented on src/components/DateRange.tsx
> +  const dateRangeData: any = [
I will suggest you to create a `config` file and add ranges in that file.

2021-10-24 19:01 UTC, Farhan-Nazir commented on src/components/StocksChart.tsx
>      const data = formattedData.map((obj: any) => obj.priceData["2. high"]);
please try to add type instead of `any`

2021-10-26 11:46 UTC, Farhan-Nazir requested changes

2021-10-26 11:46 UTC, Farhan-Nazir commented on src/components/DateRange.tsx
> +      {dateRangeData.map((range: any, i: number) => {
Set type please

2021-10-26 11:46 UTC, Farhan-Nazir commented on src/types.d.ts
> +      [key: string]: any;
Set type please

2021-10-26 12:08 UTC, Abdull-Rauf commented on src/components/DateRange.tsx
> +      {dateRangeData.map((range: any, i: number) => {
added types

2021-10-26 12:09 UTC, Abdull-Rauf commented on src/types.d.ts
> +      [key: string]: any;
types added

2021-10-26 15:44 UTC, Farhan-Nazir approved these changes

2021-10-26 18:00 UTC, merged